import { Input } from "~/components/Input";
import { type NextPage } from "next";
import Head from "next/head";
import Layout from "~/components/Layout";
import styles from "~/styles/Home.module.css"
import { Text } from "@mantine/core";
import { useUser } from "@clerk/nextjs";
import HomeWithoutUser from "~/components/HomeWithoutUser";


const Home: NextPage = () => {
  const user = useUser()

  if (!user.isLoaded) return null;

  const fullName = (user.user?.firstName ?? "") + " " + (user.user?.lastName ?? "")

  return (
    <>
      <Head>
        <title>Encodeo | invento&apos;23</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.homeMain}>
          <div className={styles.content}>
            {user.isSignedIn ? (
              <>
                <Text
                  mb="xl"
                  ml="xl"
                  color="var(--secondary-clr)"
                  component="h3"
                  fz="md"
                >Hi,
                  <br />
                  <Text
                    fw="bolder"
                    fz="xl"
                    component="span"
                  >
                    {fullName.trim()} 👋
                  </Text>
                </Text>

                <Text
                  ta="center"
                  variant="gradient"
                  gradient={{ from: "darkblue", to: "cyan", deg: 0 }}
                  fz="2.5rem"
                  component="h1"
                  fw="bolder"
                >
                  Enter the code
                </Text>
                <Input />
              </>
            ) : <HomeWithoutUser />}
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Home;
