import { Input } from "~/components/Input";
import { type NextPage } from "next";
import Head from "next/head";
import Layout from "~/components/Layout";
import styles from "~/styles/Home.module.css"
import { api } from "~/utils/api";


const Home: NextPage = () => {
  const questions = api.question.get.useQuery();
  console.log(questions.data)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.homeMain}>
          <div className={styles.content}>
            <h1>Enter a code</h1>
            <Input />
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Home;
